"use strict";
window.OLDROOT_LOCATIONS = {
    tucson: {
      id: "LOC-001",
      name: "Tucson, Arizona",
      shortName: "Tucson",
      type: "Primary operating location",
      region: "United States",
      status: "Established",
      character: "Gila Monster",
      characterUrl: "characters/gila-monster/",
      characters: [{ name: "Gila Monster", url: "characters/gila-monster/", role: "Hero" }],
      dossierUrl: "locations/tucson/",
      note: "Tucson is the established operating city of Gila Monster.",
      coords: [-110.9747, 32.2226],
      labelOffset: [11, -10]
    },
    chicago: {
      id: "LOC-002",
      name: "Chicago, Illinois",
      shortName: "Chicago",
      type: "Primary operating location",
      region: "United States",
      status: "Established",
      character: "Commotion",
      characterUrl: "characters/commotion/",
      characters: [{ name: "Commotion", url: "characters/commotion/", role: "Hero" }],
      dossierUrl: "locations/chicago/",
      note: "Chicago is the established operating city of Commotion.",
      coords: [-87.6298, 41.8781],
      labelOffset: [11, -10]
    },
    sanjuan: {
      id: "LOC-003",
      name: "San Juan, Puerto Rico",
      shortName: "San Juan",
      type: "Primary operating location",
      region: "Puerto Rico",
      status: "Established",
      character: "Aftermark",
      characterUrl: "characters/aftermark/",
      characters: [{ name: "Aftermark", url: "characters/aftermark/", role: "Hero" }],
      dossierUrl: "locations/san-juan/",
      note: "Santurce, San Juan is the established home and operating location of Aftermark.",
      coords: [-66.1057, 18.4655],
      labelOffset: [11, -10]
    },
    stdorsey: {
      id: "LOC-004",
      name: "St. Dorsey Island",
      shortName: "St. Dorsey",
      type: "Genesis location",
      region: "Greater Washington, D.C. area",
      status: "Established / schematic placement",
      character: "—",
      characterUrl: "",
      characters: [],
      dossierUrl: "locations/st-dorsey/",
      note: "St. Dorsey is the Genesis site and later home of Hampton’s rebuilt Dorsey New General Facility. Its globe marker is schematic; exact public coordinates are not established.",
      coords: [-77.0369, 38.9072],
      approximate: true,
      labelOffset: [-72, 18]
    },
    baltimore: {
      id: "LOC-005",
      name: "Baltimore, Maryland",
      shortName: "Baltimore",
      type: "Primary operating location",
      region: "United States",
      status: "Established",
      character: "Kincast · Anchorage",
      characterUrl: "",
      characters: [
        { name: "Kincast", url: "characters/kincast/", role: "Hero" },
        { name: "Anchorage", url: "characters/anchorage/", role: "Villain" }
      ],
      dossierUrl: "locations/baltimore/",
      note: "Baltimore is the established home base and primary operating city of Kincast and an established operating city of Anchorage.",
      coords: [-76.6122, 39.2904],
      labelOffset: [13, -14]
    },
    seattle: {
      id: "LOC-006",
      name: "Seattle / Puget Sound",
      shortName: "Seattle",
      type: "Primary operating location",
      region: "United States",
      status: "Established",
      character: "Agent Emerald",
      characterUrl: "characters/agent-emerald/",
      characters: [{ name: "Agent Emerald", url: "characters/agent-emerald/", role: "Vigilante" }],
      dossierUrl: "locations/seattle/",
      note: "Seattle and the Puget Sound region are the established primary location of Agent Emerald.",
      coords: [-122.3321, 47.6062],
      labelOffset: [11, -10]
    },
    hilo: {
      id: "LOC-007",
      name: "Hilo, Hawaiʻi Island",
      shortName: "Hilo",
      type: "Home base / primary operating location",
      region: "Hawaiʻi, United States",
      status: "Established",
      character: "Kokio",
      characterUrl: "characters/kokio/",
      characters: [{ name: "Kokio", url: "characters/kokio/", role: "Hero" }],
      dossierUrl: "locations/hilo/",
      note: "Hilo and eastern Hawaiʻi Island are Kokio’s established home base and primary operating region.",
      coords: [-155.09, 19.7074],
      labelOffset: [11, -10]
    },
    australia: {
      id: "REF-002",
      name: "Australia",
      shortName: "Australia",
      type: "Character geographic reference",
      region: "Australia",
      status: "Reference",
      character: "Latch",
      characterUrl: "characters/latch/",
      characters: [{ name: "Latch", url: "characters/latch/", role: "Hero recruiter / field operative" }],
      dossierUrl: "",
      note: "Australia is Latch Boswell’s established nationality and military origin. No specific Australian hometown or present-day base is established.",
      coords: [134.4896, -25.7349],
      reference: true,
      labelOffset: [11, -10]
    },
    washington: {
      id: "REF-001",
      name: "Washington, D.C.",
      shortName: "Washington, D.C.",
      type: "Geographic reference",
      region: "United States",
      status: "Reference",
      character: "—",
      characterUrl: "",
      characters: [],
      dossierUrl: "",
      note: "Washington, D.C. is shown as a geographic reference for the greater D.C. cluster and St. Dorsey's schematic placement.",
      coords: [-77.0369, 38.9072],
      reference: true,
      labelOffset: [12, 18]
    }
  };
